import classes from "./Projects.module.css";
import styles from "../styles/shared.module.css";

function Projects() {
  return (
    <div className={classes["projects__container"]} id="projects">
      <h2 className={styles["section__title"]}>projects</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, eveniet atque? Explicabo quod eos delectus error. Consequatur voluptatibus alias est harum aliquid quas odit consectetur nemo, earum quam omnis quaerat quo facere. Soluta nesciunt, nemo delectus molestias voluptas explicabo velit fuga nobis cum nulla pariatur cupiditate. Ipsa odit dolorum minus nulla quas velit voluptates molestiae? Dolorum aliquid similique rem dicta magni adipisci possimus amet ex? Accusamus quibusdam ea illo ut necessitatibus amet provident quam, minus, ad aut quisquam corrupti, dignissimos sapiente consequatur dolorum autem eum cupiditate. Optio exercitationem corporis in consectetur? Laborum laudantium tenetur natus similique, facilis eveniet provident id.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, eveniet atque? Explicabo quod eos delectus error. Consequatur voluptatibus alias est harum aliquid quas odit consectetur nemo, earum quam omnis quaerat quo facere. Soluta nesciunt, nemo delectus molestias voluptas explicabo velit fuga nobis cum nulla pariatur cupiditate. Ipsa odit dolorum minus nulla quas velit voluptates molestiae? Dolorum aliquid similique rem dicta magni adipisci possimus amet ex? Accusamus quibusdam ea illo ut necessitatibus amet provident quam, minus, ad aut quisquam corrupti, dignissimos sapiente consequatur dolorum autem eum cupiditate. Optio exercitationem corporis in consectetur? Laborum laudantium tenetur natus similique, facilis eveniet provident id.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, eveniet atque? Explicabo quod eos delectus error. Consequatur voluptatibus alias est harum aliquid quas odit consectetur nemo, earum quam omnis quaerat quo facere. Soluta nesciunt, nemo delectus molestias voluptas explicabo velit fuga nobis cum nulla pariatur cupiditate. Ipsa odit dolorum minus nulla quas velit voluptates molestiae? Dolorum aliquid similique rem dicta magni adipisci possimus amet ex? Accusamus quibusdam ea illo ut necessitatibus amet provident quam, minus, ad aut quisquam corrupti, dignissimos sapiente consequatur dolorum autem eum cupiditate. Optio exercitationem corporis in consectetur? Laborum laudantium tenetur natus similique, facilis eveniet provident id.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, eveniet atque? Explicabo quod eos delectus error. Consequatur voluptatibus alias est harum aliquid quas odit consectetur nemo, earum quam omnis quaerat quo facere. Soluta nesciunt, nemo delectus molestias voluptas explicabo velit fuga nobis cum nulla pariatur cupiditate. Ipsa odit dolorum minus nulla quas velit voluptates molestiae? Dolorum aliquid similique rem dicta magni adipisci possimus amet ex? Accusamus quibusdam ea illo ut necessitatibus amet provident quam, minus, ad aut quisquam corrupti, dignissimos sapiente consequatur dolorum autem eum cupiditate. Optio exercitationem corporis in consectetur? Laborum laudantium tenetur natus similique, facilis eveniet provident id.</p>
    </div>
  )
}

export default Projects;
